#!/bin/bash
set -e

echo "=== Создание пользователя БД ==="

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL

CREATE ROLE $SERVICE_DB_USER WITH LOGIN PASSWORD '$SERVICE_DB_PASSWORD';
CREATE EXTENSION IF NOT EXISTS citext;

ALTER DEFAULT PRIVILEGES 
  FOR ROLE $POSTGRES_USER
  IN SCHEMA public 
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $SERVICE_DB_USER;

ALTER DEFAULT PRIVILEGES 
  FOR ROLE $POSTGRES_USER
  IN SCHEMA public 
  GRANT USAGE, SELECT ON SEQUENCES TO $SERVICE_DB_USER;
EOSQL

echo "=== Инициализация пользователя завершена ==="